// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUE9qMtyI4i0DRPGb4Kx0mftpRSmXYQ3M',
    appId: '1:119032565865:web:de2ed0306b418952f5d2f8',
    messagingSenderId: '119032565865',
    projectId: 'meditation4-271cb',
    authDomain: 'meditation4-271cb.firebaseapp.com',
    storageBucket: 'meditation4-271cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuUN_SwTZ6NMR2JQw8MvuENmX8xkB6xuk',
    appId: '1:119032565865:android:9ba6d93d8445d12ef5d2f8',
    messagingSenderId: '119032565865',
    projectId: 'meditation4-271cb',
    storageBucket: 'meditation4-271cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCukxoD2RKvnbDxo9G5dNQEQnxJZYsWd8Y',
    appId: '1:119032565865:ios:ce52918a0e53fdf2f5d2f8',
    messagingSenderId: '119032565865',
    projectId: 'meditation4-271cb',
    storageBucket: 'meditation4-271cb.appspot.com',
    iosClientId: '119032565865-1kl408vsqk2arqj1bs69nmvvfbf4am96.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditation4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCukxoD2RKvnbDxo9G5dNQEQnxJZYsWd8Y',
    appId: '1:119032565865:ios:0235a162860ec3e6f5d2f8',
    messagingSenderId: '119032565865',
    projectId: 'meditation4-271cb',
    storageBucket: 'meditation4-271cb.appspot.com',
    iosClientId: '119032565865-fgc1e6u26ck5jr739g27sb05f1vuqh4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditation4.RunnerTests',
  );
}
